/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {  useState } from "react";
import * as THREE from "three";
import { useGLTF,useVideoTexture } from "@react-three/drei";
import sports from "/videos/Deportes.mp4";
import me from "/videos/Me.mp4";
import twitch from "/videos/Twitch.mp4"
import music from "/videos/Dis_Spotify.mp4"



function VideoMaterial({ url }) {
  const texture = useVideoTexture(url)
  texture.flipY = false
  return <meshBasicMaterial side={THREE.DoubleSide} map={texture} toneMapped={false} />
}

export function MeScreens(props) {
  const { nodes, materials } = useGLTF("/models/Me_Screens.gltf");

  const twitchUrl = 'https://www.twitch.tv/poncius';

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pantalla_Centro.geometry}

      >
        <VideoMaterial url={sports}/>
      </mesh>
      
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pantalla_Izquierda.geometry}
        
      >
        <VideoMaterial url={me}/>
      </mesh>
      <mesh 
        castShadow
        receiveShadow
        geometry={nodes.Pantalla_Derecha.geometry}
      
      >
        <VideoMaterial url={twitch}/>
      </mesh>
      
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pantalla_Vertical.geometry}
       
      >
        <VideoMaterial url={music}/>
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/Me_Screens.gltf");