/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import * as THREE from 'three';
import { useGLTF, useTexture} from "@react-three/drei";


export function AssetsRoom(props) {
  const { nodes, materials } = useGLTF("/models/AssetsRoom.gltf");
  
  const createTexture = (path) => {
    const texture = useTexture(path);
    texture.flipY = false;
    texture.encoding = THREE.sRGBEncoding;
    return texture;
  };

  const propsTexture = createTexture("/texture/Props.png");
  const pudTexture = createTexture("/texture/Pud.png");
  const arcadeTexture = createTexture("/texture/Arcade.png");
  const postersTexture = createTexture("/texture/Posters.png");
  const plantsTexture = createTexture("/texture/Plants.png");
  const buzzTexture = createTexture("/texture/Buzz.png");

  const glassMaterial = new THREE.MeshPhysicalMaterial({
    color: '#717482',
    transparent: true,
    opacity: 0.5,
    roughness: 0.0,
    metalness: 0.5,
    clearcoat: 1,
    ior: .25,
    clearcoatRoughness: 0.1,
  })


  //Change Materials 
  materials.Props.map = propsTexture
  materials.PUD.map = pudTexture
  materials.Arcade.map = arcadeTexture
  materials.Poster.map = postersTexture
  materials.Plants.map = plantsTexture
  materials.Buzz.map = buzzTexture

  return (
    <group {...props} dispose={null}>
    <mesh
      name="Blonde"
      castShadow
      receiveShadow
      geometry={nodes.Blonde.geometry}
      material={materials.Poster}
    />
    <mesh
      name="Circles"
      castShadow
      receiveShadow
      geometry={nodes.Circles.geometry}
      material={materials.Poster}
    />
    <mesh
      name="MF_Doom"
      castShadow
      receiveShadow
      geometry={nodes.MF_Doom.geometry}
      material={materials.Poster}
    />
    <mesh
      name="Minecraft"
      castShadow
      receiveShadow
      geometry={nodes.Minecraft.geometry}
      material={materials.Poster}
    />
    <mesh
      name="Plane001"
      castShadow
      receiveShadow
      geometry={nodes.Plane001.geometry}
      material={materials.Poster}
    />
    <mesh
      name="Plane002"
      castShadow
      receiveShadow
      geometry={nodes.Plane002.geometry}
      material={materials.Poster}
    />
    <mesh
      name="Plane010"
      castShadow
      receiveShadow
      geometry={nodes.Plane010.geometry}
      material={materials.Poster}
    />
    <mesh
      name="Plane011"
      castShadow
      receiveShadow
      geometry={nodes.Plane011.geometry}
      material={materials.Poster}
    />
    <mesh
      name="Poster_Largo"
      castShadow
      receiveShadow
      geometry={nodes.Poster_Largo.geometry}
      material={materials.Poster}
    />
    <mesh
      name="Tablero_Basket"
      castShadow
      receiveShadow
      geometry={nodes.Tablero_Basket.geometry}
      material={materials.Poster}
    />
    <mesh
      name="TerarioPequeño"
      castShadow
      receiveShadow
      geometry={nodes.TerarioPequeño.geometry}
      material={materials.Poster}
    />
    <mesh
      name="TerrarioGrande001"
      castShadow
      receiveShadow
      geometry={nodes.TerrarioGrande001.geometry}
      material={materials.Poster}
    />
    <mesh
      name="2"
      castShadow
      receiveShadow
      geometry={nodes['2'].geometry}
      material={materials.Plants}
    />
    <mesh
      name="2001"
      castShadow
      receiveShadow
      geometry={nodes['2001'].geometry}
      material={materials.Plants}
    />
    <mesh
      name="2002"
      castShadow
      receiveShadow
      geometry={nodes['2002'].geometry}
      material={materials.Plants}
    />
    <mesh
      name="2003"
      castShadow
      receiveShadow
      geometry={nodes['2003'].geometry}
      material={materials.Plants}
    />
    <mesh
      name="2004"
      castShadow
      receiveShadow
      geometry={nodes['2004'].geometry}
      material={materials.Plants}
    />
    <mesh
      name="2005"
      castShadow
      receiveShadow
      geometry={nodes['2005'].geometry}
      material={materials.Plants}
    />
    <mesh
      name="4A"
      castShadow
      receiveShadow
      geometry={nodes['4A'].geometry}
      material={materials.Plants}
    />
    <mesh
      name="4A001"
      castShadow
      receiveShadow
      geometry={nodes['4A001'].geometry}
      material={materials.Plants}
    />
    <mesh
      name="4A002"
      castShadow
      receiveShadow
      geometry={nodes['4A002'].geometry}
      material={materials.Plants}
    />
    <mesh
      name="4A003"
      castShadow
      receiveShadow
      geometry={nodes['4A003'].geometry}
      material={materials.Plants}
    />
    <mesh
      name="4A004"
      castShadow
      receiveShadow
      geometry={nodes['4A004'].geometry}
      material={materials.Plants}
    />
    <mesh
      name="4A005"
      castShadow
      receiveShadow
      geometry={nodes['4A005'].geometry}
      material={materials.Plants}
    />
    <mesh
      name="4A006"
      castShadow
      receiveShadow
      geometry={nodes['4A006'].geometry}
      material={materials.Plants}
    />
    <mesh
      name="4A007"
      castShadow
      receiveShadow
      geometry={nodes['4A007'].geometry}
      material={materials.Plants}
    />
    <mesh
      name="4A008"
      castShadow
      receiveShadow
      geometry={nodes['4A008'].geometry}
      material={materials.Plants}
    />
    <mesh
      name="4A009"
      castShadow
      receiveShadow
      geometry={nodes['4A009'].geometry}
      material={materials.Plants}
    />
    <mesh
      name="4A010"
      castShadow
      receiveShadow
      geometry={nodes['4A010'].geometry}
      material={materials.Plants}
    />
    <mesh
      name="4A011"
      castShadow
      receiveShadow
      geometry={nodes['4A011'].geometry}
      material={materials.Plants}
    />
    <mesh
      name="4A012"
      castShadow
      receiveShadow
      geometry={nodes['4A012'].geometry}
      material={materials.Plants}
    />
    <mesh
      name="maceta"
      castShadow
      receiveShadow
      geometry={nodes.maceta.geometry}
      material={materials.Plants}
    />
    <mesh
      name="maceta1"
      castShadow
      receiveShadow
      geometry={nodes.maceta1.geometry}
      material={materials.Plants}
    />
    <mesh
      name="maceta2"
      castShadow
      receiveShadow
      geometry={nodes.maceta2.geometry}
      material={materials.Plants}
    />
    <mesh
      name="BotonD"
      castShadow
      receiveShadow
      geometry={nodes.BotonD.geometry}
      material={materials.Arcade}
    />
    <mesh
      name="BotonD001"
      castShadow
      receiveShadow
      geometry={nodes.BotonD001.geometry}
      material={materials.Arcade}
    />
    <mesh
      name="BotonD002"
      castShadow
      receiveShadow
      geometry={nodes.BotonD002.geometry}
      material={materials.Arcade}
    />
    <mesh
      name="Botones"
      castShadow
      receiveShadow
      geometry={nodes.Botones.geometry}
      material={materials.Arcade}
    />
    <mesh
      name="Botones001"
      castShadow
      receiveShadow
      geometry={nodes.Botones001.geometry}
      material={materials.Arcade}
    />
    <mesh
      name="Monedas"
      castShadow
      receiveShadow
      geometry={nodes.Monedas.geometry}
      material={materials.Arcade}
    />
    <mesh
      name="Palanca"
      castShadow
      receiveShadow
      geometry={nodes.Palanca.geometry}
      material={materials.Arcade}
    />
    <mesh
      name="Palanca001"
      castShadow
      receiveShadow
      geometry={nodes.Palanca001.geometry}
      material={materials.Arcade}
    />
    <mesh
      name="Arcade"
      castShadow
      receiveShadow
      geometry={nodes.Arcade.geometry}
      material={materials.Arcade}
    />
    <mesh
      name="Base"
      castShadow
      receiveShadow
      geometry={nodes.Base.geometry}
      material={materials.PUD}
    />
    <mesh
      name="pCylinder50001"
      castShadow
      receiveShadow
      geometry={nodes.pCylinder50001.geometry}
      material={materials.PUD}
      position={[-71.008, 99.975, -64.153]}
    />
    <mesh
      name="pCylinder51001"
      castShadow
      receiveShadow
      geometry={nodes.pCylinder51001.geometry}
      material={materials.PUD}
      position={[-71.004, 99.958, -65.071]}
    />
    <mesh
      name="pCylinder52001"
      castShadow
      receiveShadow
      geometry={nodes.pCylinder52001.geometry}
      material={materials.PUD}
      position={[-71.008, 99.975, -65.987]}
    />
    <mesh
      name="pCylinder53001"
      castShadow
      receiveShadow
      geometry={nodes.pCylinder53001.geometry}
      material={materials.PUD}
    />
    <mesh
      name="pCylinder54001"
      castShadow
      receiveShadow
      geometry={nodes.pCylinder54001.geometry}
      material={materials.PUD}
    />
    <mesh
      name="pCylinder55001"
      castShadow
      receiveShadow
      geometry={nodes.pCylinder55001.geometry}
      material={materials.PUD}
    />
    <mesh
      name="pCylinder56001"
      castShadow
      receiveShadow
      geometry={nodes.pCylinder56001.geometry}
      material={materials.PUD}
    />
    <mesh
      name="pCylinder57001"
      castShadow
      receiveShadow
      geometry={nodes.pCylinder57001.geometry}
      material={materials.PUD}
      position={[-76.298, 100.137, -37.736]}
    />
    <mesh
      name="pCylinder58001"
      castShadow
      receiveShadow
      geometry={nodes.pCylinder58001.geometry}
      material={materials.PUD}
      position={[-76.298, 100.137, -38.737]}
    />
    <mesh
      name="pCylinder59001"
      castShadow
      receiveShadow
      geometry={nodes.pCylinder59001.geometry}
      material={materials.PUD}
      position={[-76.298, 100.137, -36.941]}
    />
    <mesh
      name="pCylinder60001"
      castShadow
      receiveShadow
      geometry={nodes.pCylinder60001.geometry}
      material={materials.PUD}
      position={[-76.847, 100.041, -25.911]}
      scale={[1, 1.165, 1]}
    />
    <mesh
      name="pCylinder61001"
      castShadow
      receiveShadow
      geometry={nodes.pCylinder61001.geometry}
      material={materials.PUD}
      position={[-76.847, 100.041, -24.873]}
      scale={[1, 1.165, 1]}
    />
    <mesh
      name="pCylinder62001"
      castShadow
      receiveShadow
      geometry={nodes.pCylinder62001.geometry}
      material={materials.PUD}
      position={[-75.828, 101.278, -23.792]}
      scale={[1, 1.165, 1]}
    />
    <mesh
      name="pCylinder63001"
      castShadow
      receiveShadow
      geometry={nodes.pCylinder63001.geometry}
      material={materials.PUD}
      position={[-76.817, 100.4, -46.468]}
    />
    <mesh
      name="pCylinder64001"
      castShadow
      receiveShadow
      geometry={nodes.pCylinder64001.geometry}
      material={materials.PUD}
      position={[-75.454, 100.4, -47.136]}
    />
    <mesh
      name="pCylinder65002"
      castShadow
      receiveShadow
      geometry={nodes.pCylinder65002.geometry}
      material={materials.PUD}
    />
    <mesh
      name="pCylinder65003"
      castShadow
      receiveShadow
      geometry={nodes.pCylinder65003.geometry}
      material={materials.PUD}
    />
    <mesh
      name="plataforma"
      castShadow
      receiveShadow
      geometry={nodes.plataforma.geometry}
      material={materials.PUD}
    />
    <mesh
      name="polySurface107"
      castShadow
      receiveShadow
      geometry={nodes.polySurface107.geometry}
      material={materials.PUD}
    />
    <mesh
      name="Tapa"
      castShadow
      receiveShadow
      geometry={nodes.Tapa.geometry}
      material={materials.PUD}
    />
    <mesh
      name="Aro001"
      castShadow
      receiveShadow
      geometry={nodes.Aro001.geometry}
      material={materials.Props}
    />
    <mesh
      name="book004"
      castShadow
      receiveShadow
      geometry={nodes.book004.geometry}
      material={materials.Props}
    />
    <mesh
      name="book006"
      castShadow
      receiveShadow
      geometry={nodes.book006.geometry}
      material={materials.Props}
    />
    <mesh
      name="book007"
      castShadow
      receiveShadow
      geometry={nodes.book007.geometry}
      material={materials.Props}
    />
    <mesh
      name="book009"
      castShadow
      receiveShadow
      geometry={nodes.book009.geometry}
      material={materials.Props}
    />
    <mesh
      name="book010"
      castShadow
      receiveShadow
      geometry={nodes.book010.geometry}
      material={materials.Props}
    />
    <mesh
      name="book011"
      castShadow
      receiveShadow
      geometry={nodes.book011.geometry}
      material={materials.Props}
    />
    <mesh
      name="book012"
      castShadow
      receiveShadow
      geometry={nodes.book012.geometry}
      material={materials.Props}
    />
    <mesh
      name="CajaRadianita"
      castShadow
      receiveShadow
      geometry={nodes.CajaRadianita.geometry}
      material={materials.Props}
    />
    <mesh
      name="Cube"
      castShadow
      receiveShadow
      geometry={nodes.Cube.geometry}
      material={materials.Props}
    />
    <mesh
      name="Cube002"
      castShadow
      receiveShadow
      geometry={nodes.Cube002.geometry}
      material={materials.Props}
    />
    <mesh
      name="Espada3"
      castShadow
      receiveShadow
      geometry={nodes.Espada3.geometry}
      material={materials.Props}
    />
    <mesh
      name="pizarron"
      castShadow
      receiveShadow
      geometry={nodes.pizarron.geometry}
      material={materials.Props}
    />
    <mesh
      name="buzz_lightyear"
      castShadow
      receiveShadow
      geometry={nodes.buzz_lightyear.geometry}
      material={materials.Buzz}
    />
    <mesh
      name="Cristal_Esquina"
      castShadow
      receiveShadow
      geometry={nodes.Cristal_Esquina.geometry}
      material={glassMaterial}
    />
    <mesh
      name="Cristal_Pecera_CH"
      castShadow
      receiveShadow
      geometry={nodes.Cristal_Pecera_CH.geometry}
      material={glassMaterial}
    />
    <mesh
      name="Cristal_Pecera_G"
      castShadow
      receiveShadow
      geometry={nodes.Cristal_Pecera_G.geometry}
      material={glassMaterial}
    />
    <mesh
      name="Cristal_Pud"
      castShadow
      receiveShadow
      geometry={nodes.Cristal_Pud.geometry}
      material={glassMaterial}
    />
    <mesh
      name="Refrigerador_Cristal_"
      castShadow
      receiveShadow
      geometry={nodes.Refrigerador_Cristal_.geometry}
      material={glassMaterial}
      position={[-65.035, 83.628, 10.951]}
    />
    <mesh
      name="Tornillo"
      castShadow
      receiveShadow
      geometry={nodes.Tornillo.geometry}
      material={materials.PUD}
      position={[0.204, -0.008, -0.08]}
      rotation={[Math.PI / 2, 0, 0.209]}
      scale={0.01}
    />
    <mesh
      name="Tornillo001"
      castShadow
      receiveShadow
      geometry={nodes.Tornillo001.geometry}
      material={materials.PUD}
      position={[0.204, -0.008, -0.08]}
      rotation={[Math.PI / 2, 0, 0.209]}
      scale={0.01}
    />
    <mesh
      name="Tornillo002"
      castShadow
      receiveShadow
      geometry={nodes.Tornillo002.geometry}
      material={materials.PUD}
      position={[0.204, -0.008, -0.08]}
      rotation={[Math.PI / 2, 0, 0.209]}
      scale={0.01}
    />
    <mesh
      name="Tornillo003"
      castShadow
      receiveShadow
      geometry={nodes.Tornillo003.geometry}
      material={materials.PUD}
      position={[0.204, -0.008, -0.08]}
      rotation={[Math.PI / 2, 0, 0.209]}
      scale={0.01}
    />
    <mesh
      name="Tornillos"
      castShadow
      receiveShadow
      geometry={nodes.Tornillos.geometry}
      material={materials.PUD}
      position={[0.204, -0.008, -0.08]}
      rotation={[Math.PI / 2, 0, 0.209]}
      scale={0.01}
    />
    <mesh
      name="Tubo001"
      castShadow
      receiveShadow
      geometry={nodes.Tubo001.geometry}
      material={materials.PUD}
      position={[0.204, -0.008, -0.08]}
      rotation={[Math.PI / 2, 0, 0.209]}
      scale={0.01}
    />
    <mesh
      name="Tubo002"
      castShadow
      receiveShadow
      geometry={nodes.Tubo002.geometry}
      material={materials.PUD}
      position={[0.204, -0.008, -0.08]}
      rotation={[Math.PI / 2, 0, 0.209]}
      scale={0.01}
    />
    <mesh
      name="Tubo003"
      castShadow
      receiveShadow
      geometry={nodes.Tubo003.geometry}
      material={materials.PUD}
      position={[0.204, -0.008, -0.08]}
      rotation={[Math.PI / 2, 0, 0.209]}
      scale={0.01}
    />
    <mesh
      name="Tubo004"
      castShadow
      receiveShadow
      geometry={nodes.Tubo004.geometry}
      material={materials.PUD}
      position={[0.204, -0.008, -0.08]}
      rotation={[Math.PI / 2, 0, 0.209]}
      scale={0.01}
    />
    <mesh
      name="cables001"
      castShadow
      receiveShadow
      geometry={nodes.cables001.geometry}
      material={materials.PUD}
      rotation={[Math.PI / 2, 0, 0]}
      scale={0.01}
    />
  </group>
  );
}

useGLTF.preload("/models/AssetsRoom.gltf");
