
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import * as THREE from 'three';
import { useGLTF,useTexture } from '@react-three/drei'

export function BaseRoom(props) {
  const { nodes, materials } = useGLTF("/models/BaseRoom.gltf")


  const createTexture = (path) => {
    const texture = useTexture(path);
    texture.flipY = false;
    texture.encoding = THREE.sRGBEncoding;
    return texture;
  };
  
  // Textures
  const baseTexture = createTexture("/texture/BaseRoom.png");
  const secondFloorTexture = createTexture("/texture/SegundoPiso.png");
  const desktopTexture = createTexture("/texture/Desktop.png");
  const terrariumTexture = createTexture("/texture/Peceras.png");


  // Change Materials
  materials.CuartoBase.map = baseTexture;
  materials.Desktop.map = desktopTexture;
  materials.SegundoPiso.map = secondFloorTexture;
  materials.Pecera.map = terrariumTexture;




  return (
    <group {...props} dispose={null}>
      <mesh
        name="escritorio001"
        castShadow
        receiveShadow
        geometry={nodes.escritorio001.geometry}
        material={materials.Desktop}
        position={[-53.678, 87.424, -36.575]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.557}
      />
      <mesh
        name="Marco_Monitores002"
        castShadow
        receiveShadow
        geometry={nodes.Marco_Monitores002.geometry}
        material={materials.Desktop}
        position={[-68.743, 112.204, -62.288]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.557}
      />
      <mesh
        name="PC1002"
        castShadow
        receiveShadow
        geometry={nodes.PC1002.geometry}
        material={materials.Desktop}
        position={[-66.958, 80.892, -39.476]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.557}
      />
      <mesh
        name="PC2002"
        castShadow
        receiveShadow
        geometry={nodes.PC2002.geometry}
        material={materials.Desktop}
        position={[-60.853, 80.892, -61.528]}
        rotation={[Math.PI / 2, 0, -0.655]}
        scale={0.557}
      />
      <mesh
        name="polySurface133001"
        castShadow
        receiveShadow
        geometry={nodes.polySurface133001.geometry}
        material={materials.Desktop}
        position={[-59.334, 88.143, -15.036]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.557}
      />
      <mesh
        name="Ps4002"
        castShadow
        receiveShadow
        geometry={nodes.Ps4002.geometry}
        material={materials.Desktop}
        position={[-69.883, 93.673, -27.929]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.557}
      />
      <mesh
        name="Silla001"
        castShadow
        receiveShadow
        geometry={nodes.Silla001.geometry}
        material={materials.Desktop}
        position={[-48.719, 85.467, -34.949]}
        rotation={[Math.PI / 2, 0, 0.73]}
        scale={0.557}
      />
      <mesh
        name="Xbox360002"
        castShadow
        receiveShadow
        geometry={nodes.Xbox360002.geometry}
        material={materials.Desktop}
        position={[-69.193, 96.338, -20.922]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.557}
      />
      <mesh
        name="polySurface136001"
        castShadow
        receiveShadow
        geometry={nodes.polySurface136001.geometry}
        material={materials.Desktop}
        position={[-59.334, 77.809, -15.036]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.557}
      />
      <mesh
        name="Marco_Principal"
        castShadow
        receiveShadow
        geometry={nodes.Marco_Principal.geometry}
        material={materials.Desktop}
        position={[-74.869, 104.857, -43.231]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.557, 0.671, 0.673]}
      />
      <mesh
        name="Marco_Izquierda"
        castShadow
        receiveShadow
        geometry={nodes.Marco_Izquierda.geometry}
        material={materials.Desktop}
        position={[-73.236, 112.789, -23.21]}
        rotation={[Math.PI / 2, 0, -0.233]}
        scale={0.701}
      />
      <mesh
        name="Marco_Arriba"
        castShadow
        receiveShadow
        geometry={nodes.Marco_Arriba.geometry}
        material={materials.Desktop}
        position={[-74.559, 119.913, -41.902]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.815}
      />
      <mesh
        name="lata001"
        castShadow
        receiveShadow
        geometry={nodes.lata001.geometry}
        material={materials.Desktop}
        position={[-68.627, 84.589, 11.955]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.557}
      />
      <mesh
        name="lata1001"
        castShadow
        receiveShadow
        geometry={nodes.lata1001.geometry}
        material={materials.Desktop}
        position={[-68.627, 84.589, 14.41]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.557}
      />
      <mesh
        name="lata2001"
        castShadow
        receiveShadow
        geometry={nodes.lata2001.geometry}
        material={materials.Desktop}
        position={[-68.627, 84.589, 9.55]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.557}
      />
      <mesh
        name="lata3001"
        castShadow
        receiveShadow
        geometry={nodes.lata3001.geometry}
        material={materials.Desktop}
        position={[-68.627, 84.589, 7.083]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.557}
      />
      <mesh
        name="lata4001"
        castShadow
        receiveShadow
        geometry={nodes.lata4001.geometry}
        material={materials.Desktop}
        position={[-68.627, 86.24, 8.225]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.557}
      />
      <mesh
        name="lata5001"
        castShadow
        receiveShadow
        geometry={nodes.lata5001.geometry}
        material={materials.Desktop}
        position={[-67.679, 78.118, 15.402]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.557}
      />
      <mesh
        name="lata6001"
        castShadow
        receiveShadow
        geometry={nodes.lata6001.geometry}
        material={materials.Desktop}
        position={[-67.679, 78.118, 12.947]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.557}
      />
      <mesh
        name="lata7001"
        castShadow
        receiveShadow
        geometry={nodes.lata7001.geometry}
        material={materials.Desktop}
        position={[-68.199, 80.663, 10.032]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.557}
      />
      <mesh
        name="lata8001"
        castShadow
        receiveShadow
        geometry={nodes.lata8001.geometry}
        material={materials.Desktop}
        position={[-71.047, 80.663, 8.889]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.557}
      />
      <mesh
        name="lata9001"
        castShadow
        receiveShadow
        geometry={nodes.lata9001.geometry}
        material={materials.Desktop}
        position={[-68.673, 80.663, 6.572]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.557}
      />
      <mesh
        name="Refri_Marco001"
        castShadow
        receiveShadow
        geometry={nodes.Refri_Marco001.geometry}
        material={materials.Desktop}
        position={[-68.582, 81.699, 10.831]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.557}
      />
      <mesh
        name="Repisa_Grande1001"
        castShadow
        receiveShadow
        geometry={nodes.Repisa_Grande1001.geometry}
        material={materials.Desktop}
        position={[-71.97, 108.533, 32.671]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.557}
      />
      <mesh
        name="Repisa_Grande2001"
        castShadow
        receiveShadow
        geometry={nodes.Repisa_Grande2001.geometry}
        material={materials.Desktop}
        position={[-71.468, 114.314, 2.796]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.557}
      />
      <mesh
        name="Repisa_Grande001"
        castShadow
        receiveShadow
        geometry={nodes.Repisa_Grande001.geometry}
        material={materials.Desktop}
        position={[-68.032, 86.903, 48.373]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.557}
      />
      <mesh
        name="mouse002"
        castShadow
        receiveShadow
        geometry={nodes.mouse002.geometry}
        material={materials.Desktop}
        position={[-68.463, 93.262, -51.66]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={0.45}
      />
      <mesh
        name="base001"
        castShadow
        receiveShadow
        geometry={nodes.base001.geometry}
        material={materials.Desktop}
        position={[-67.903, 93.475, -43.683]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={0.45}
      />
      <mesh
        name="LavaLamp"
        castShadow
        receiveShadow
        geometry={nodes.LavaLamp.geometry}
        material={materials.Desktop}
        position={[-69.624, 97.816, -13.925]}
        rotation={[Math.PI / 2, 0, -0.333]}
        scale={[1.235, 1.235, 1.894]}
      />
      <mesh
        name="Lava"
        castShadow
        receiveShadow
        geometry={nodes.Lava.geometry}
        material={materials.Lava}
        position={[-69.627, 94.844, -13.914]}
        rotation={[Math.PI / 2, 0, -0.333]}
        scale={[1.393, 1.279, 1.937]}
      />
      <mesh
        name="alacena"
        castShadow
        receiveShadow
        geometry={nodes.alacena.geometry}
        material={materials.CuartoBase}
      />
      <mesh
        name="cojin1"
        castShadow
        receiveShadow
        geometry={nodes.cojin1.geometry}
        material={materials.CuartoBase}
      />
      <mesh
        name="cojin2"
        castShadow
        receiveShadow
        geometry={nodes.cojin2.geometry}
        material={materials.CuartoBase}
      />
      <mesh
        name="cojin3"
        castShadow
        receiveShadow
        geometry={nodes.cojin3.geometry}
        material={materials.CuartoBase}
      />
      <mesh
        name="escaleras_puerta"
        castShadow
        receiveShadow
        geometry={nodes.escaleras_puerta.geometry}
        material={materials.CuartoBase}
      />
      <mesh
        name="Manijas"
        castShadow
        receiveShadow
        geometry={nodes.Manijas.geometry}
        material={materials.CuartoBase}
      />
      <mesh
        name="Marco_Puerta"
        castShadow
        receiveShadow
        geometry={nodes.Marco_Puerta.geometry}
        material={materials.CuartoBase}
      />
      <mesh
        name="Marco_Ventana"
        castShadow
        receiveShadow
        geometry={nodes.Marco_Ventana.geometry}
        material={materials.CuartoBase}
      />
      <mesh
        name="Pared_D"
        castShadow
        receiveShadow
        geometry={nodes.Pared_D.geometry}
        material={materials.CuartoBase}
      />
      <mesh
        name="Pared_izq"
        castShadow
        receiveShadow
        geometry={nodes.Pared_izq.geometry}
        material={materials.CuartoBase}
      />
      <mesh
        name="Piso"
        castShadow
        receiveShadow
        geometry={nodes.Piso.geometry}
        material={materials.CuartoBase}
      />
      <mesh
        name="Puerta"
        castShadow
        receiveShadow
        geometry={nodes.Puerta.geometry}
        material={materials.CuartoBase}
      />
      <mesh
        name="sillon"
        castShadow
        receiveShadow
        geometry={nodes.sillon.geometry}
        material={materials.CuartoBase}
      />
      <mesh
        name="almohada"
        castShadow
        receiveShadow
        geometry={nodes.almohada.geometry}
        material={materials.SegundoPiso}
      />
      <mesh
        name="almohada1"
        castShadow
        receiveShadow
        geometry={nodes.almohada1.geometry}
        material={materials.SegundoPiso}
      />
      <mesh
        name="colchon"
        castShadow
        receiveShadow
        geometry={nodes.colchon.geometry}
        material={materials.SegundoPiso}
      />
      <mesh
        name="cuarto"
        castShadow
        receiveShadow
        geometry={nodes.cuarto.geometry}
        material={materials.SegundoPiso}
      />
      <mesh
        name="escaleras_cuarto"
        castShadow
        receiveShadow
        geometry={nodes.escaleras_cuarto.geometry}
        material={materials.SegundoPiso}
      />
      <mesh
        name="escaleras_pared"
        castShadow
        receiveShadow
        geometry={nodes.escaleras_pared.geometry}
        material={materials.SegundoPiso}
      />
      <mesh
        name="librero"
        castShadow
        receiveShadow
        geometry={nodes.librero.geometry}
        material={materials.SegundoPiso}
      />
      <mesh
        name="pared"
        castShadow
        receiveShadow
        geometry={nodes.pared.geometry}
        material={materials.SegundoPiso}
      />
      <mesh
        name="SegundoPiso"
        castShadow
        receiveShadow
        geometry={nodes.SegundoPiso.geometry}
        material={materials.SegundoPiso}
      />
      <mesh
        name="TerrarioGrande"
        castShadow
        receiveShadow
        geometry={nodes.TerrarioGrande.geometry}
        material={materials.SegundoPiso}
      />
      <mesh
        name="Tierra_A001"
        castShadow
        receiveShadow
        geometry={nodes.Tierra_A001.geometry}
        material={materials.SegundoPiso}
      />
      <mesh
        name="Tubo"
        castShadow
        receiveShadow
        geometry={nodes.Tubo.geometry}
        material={materials.SegundoPiso}
      />
      <mesh
        name="Tubo_Abajo"
        castShadow
        receiveShadow
        geometry={nodes.Tubo_Abajo.geometry}
        material={materials.SegundoPiso}
      />
      <mesh
        name="pecera1"
        castShadow
        receiveShadow
        geometry={nodes.pecera1.geometry}
        material={materials.Pecera}
      />
      <mesh
        name="Tapas_G"
        castShadow
        receiveShadow
        geometry={nodes.Tapas_G.geometry}
        material={materials.Pecera}
      />
      <mesh
        name="Tierra_G001"
        castShadow
        receiveShadow
        geometry={nodes.Tierra_G001.geometry}
        material={materials.Pecera}
      />
      <mesh
        name="Tierra_P001"
        castShadow
        receiveShadow
        geometry={nodes.Tierra_P001.geometry}
        material={materials.Pecera}
      />
      <mesh
        name="trunks00001"
        castShadow
        receiveShadow
        geometry={nodes.trunks00001.geometry}
        material={materials.Pecera}
      />
      <mesh
        name="trunks01002"
        castShadow
        receiveShadow
        geometry={nodes.trunks01002.geometry}
        material={materials.Pecera}
      />
      <mesh
        name="trunks01003"
        castShadow
        receiveShadow
        geometry={nodes.trunks01003.geometry}
        material={materials.Pecera}
      />
      <mesh
        name="trunks03002"
        castShadow
        receiveShadow
        geometry={nodes.trunks03002.geometry}
        material={materials.Pecera}
      />
      <mesh
        name="trunks03003"
        castShadow
        receiveShadow
        geometry={nodes.trunks03003.geometry}
        material={materials.Pecera}
      />
    </group>
  )
}

useGLTF.preload("/models/BaseRoom.gltf") 

