
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF,Html } from "@react-three/drei";


export function Arcade(props) {
  const { nodes, materials } = useGLTF("public/models/S_Arcade.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Arcade_Screen.geometry}
        material={materials.Screen}
        >
            <Html transform
            rotation={[0,0.2,0]}
            position={[79.5,90.5,-58]} 
             style={{
                backgroundColor: 'red',
                width: '100px',
                height:'100px',
                }} >
                <h1>
                    Hola Mundo
                </h1>
            </Html>
        </mesh>
    
    </group>
  );
}

useGLTF.preload("public/models/S_Arcade.gltf");
