
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF,Html } from "@react-three/drei";


export function Arcade(props) {
  const { nodes, materials } = useGLTF("/models/S_Arcade.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        //geometry={nodes.Arcade_Screen.geometry}
        //material={materials.Screen}
          >
            <Html
            className="arcade-screen"
            rotation={[-0.1,0,0]}
            position={[63,99.6,-56]}
            transform
            occlude
             >
                <h1>
                    Hola Mundo
                </h1>
            </Html>
          </mesh>
      
    </group>
  );
}
 

useGLTF.preload("/models/S_Arcade.gltf");





