/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function MeScreens(props) {
  const { nodes, materials } = useGLTF("public/models/Me_Screens.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pantalla_Centro.geometry}
        material={nodes.Pantalla_Centro.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pantalla_Izquierda.geometry}
        material={nodes.Pantalla_Izquierda.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pantalla_Derecha.geometry}
        material={nodes.Pantalla_Derecha.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pantalla_Vertical.geometry}
        material={nodes.Pantalla_Vertical.material}
      />
    </group>
  );
}

useGLTF.preload("public/models/Me_Screens.gltf");