/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function MeScreens(props) {
  const { nodes, materials } = useGLTF("public/models/Me_Screens.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pantalla_Centro1.geometry}
        material={materials.t}
        position={[-1.32, 1.99, -0.45]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pantalla_Centro2.geometry}
        material={materials.t}
        position={[-1.29, 2.24, -0.57]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pantalla_Centro3.geometry}
        material={materials.t}
        position={[-1.31, 2.05, -0.79]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pantalla_Centro5.geometry}
        material={materials.t}
        position={[-1.21, 1.91, -1.14]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload("public/models/Me_Screens.gltf");