/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF,Html } from "@react-three/drei";

export function PcScreen(props) {
  const { nodes, materials } = useGLTF("/models/PcScreen.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        //geometry={nodes.PcScreen.geometry}
        //material={materials["Screen.001"]}
      >  
      <Html 
       className="pc-screen"
        position={[-74.5,103.5,-43.8]}
        rotation={[0.,1.57,0]}
        transform
        occlude
      >
          <h1>
              Hola Mundo
          </h1>
      </Html>

      </mesh>
    </group>
  ); 
}

useGLTF.preload("/models/PcScreen.gltf");
